name: WhenFresh.Utilities.Domain.RoyalMail
on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  security-events: write
  pull-requests: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/_library.nuget.yml
    name: Build and Deploy
  